//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeHappy {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceGlobal {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceGlobal() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BeHappy.ResourceGlobal", typeof(ResourceGlobal).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Priority Warning.
        /// </summary>
        internal static string CaptionHighPriorityWarning {
            get {
                return ResourceManager.GetString("CaptionHighPriorityWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Above Normal.
        /// </summary>
        internal static string ItemPriorityAboveNormal {
            get {
                return ResourceManager.GetString("ItemPriorityAboveNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below Normal.
        /// </summary>
        internal static string ItemPriorityBelowNormal {
            get {
                return ResourceManager.GetString("ItemPriorityBelowNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string ItemPriorityHigh {
            get {
                return ResourceManager.GetString("ItemPriorityHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle.
        /// </summary>
        internal static string ItemPriorityIdle {
            get {
                return ResourceManager.GetString("ItemPriorityIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string ItemPriorityNormal {
            get {
                return ResourceManager.GetString("ItemPriorityNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running the encoder at high priority causes it to compete with other Windows processes.  Continue?.
        /// </summary>
        internal static string MsgHighPriorityWarning {
            get {
                return ResourceManager.GetString("MsgHighPriorityWarning", resourceCulture);
            }
        }
    }
}
